### PR TITLE
Moved to org file as master. Formatted to make easy to be reviewed relative to upstream

### PR DESCRIPTION
**Pull request by alanruttenberg**
Hi,

I'd like to propose we collaborate. I've moved my source to the org file, formatted with most of my changes in new sections at the bottom. I've added a new test that loads this org file, tangles to a lisp file, loads that lisp file, tangles again, and makes sure the results are the same.

If you agree you can either accept this pull and then we can reorganize the file, or we can discuss how to proceed otherwise.

Best,
Alan

### CODE REVIEW

**Comment by alanruttenberg** [comment]
Erratum: Noticed that :@= |bootstrap| isn't used. Instead defined :@@ directly earlier in file.

**Comment by alanruttenberg** [comment]
How I'm testing: [ros-tests.sh](https://github.com/alanruttenberg/literate-lisp/blob/master/t/ros-tests.sh)

**Comment by jingtaozf** [comment]
Currently literate-lisp don't support backward reference to a code block, I treat your changes as the attemps to solve this problem.

One goal of literate-lisp is to integrate with current development tools seamlessly.
For now, the org file can avoid to be tangled into a lisp file,and we can develop with SLIME progressively, that is, redefine every function by SLIME's Emacs command "slime-compile-defun" to improve every top level form by iterate.

If you have a LispWorks Editor, you can also debug such org file directly.

We also don't want to introduce much changes to exist reader, to reduce the complex and to avoid introducing unknown bugs.

In actual daily development, especially in Emacs from a scratch, we don't need the backforward reference because we can define all code blocks manually, the necessary condition is when compiling or loading an org file.

Maybe we have to find another more simple pattern to support backward reference a code block.

I am not sure(we should have a check if possible) but if Lisp Compiler does two passes over every source file, then we can try to find a way to  gather all code blocks in the first pass and expand it in the second pass.

If Lisp compiler only scan one source file once(That's also possible because lisp compiler is a simple one) then we can improve your solution to integrate with Lisp System seamlessly, at least for a SLIME development.

Finally, this commit can't pass the tests by script file ros-test.sh and can't be loaded directly by 
SLIME command "slime-compile-and-load-file".

**Comment by alanruttenberg** [comment]
I hadn't attended to the variations in different compilers and hadn't realized that the quicklisp diff package doesn't work in all lisps. I'll proceed in my development and keep an eye on yours. 
Best,
Alan

**Pull request closed without merging**
